export enum FollowUpType {
  REBOOKING = 'REBOOKING',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  SKIPPED = 'SKIPPED',
}

export enum FollowUpSkipReason {
  CUSTOMER_REBOOKED = 'CUSTOMER_REBOOKED',
  CUSTOMER_INACTIVE = 'CUSTOMER_INACTIVE',
  SETTINGS_DISABLED = 'SETTINGS_DISABLED',
  NO_WHATSAPP = 'NO_WHATSAPP',
}
